DROP TABLE SPOT_LIKE_INFO PURGE;
CREATE TABLE SPOT_LIKE_INFO (
    LIKE_IDX        NUMBER          CONSTRAINT LIKE_PK PRIMARY KEY,
    CONTENT_ID       VARCHAR2(10)    NOT NULL,
    LIKE_CNT        NUMBER
);



select * from spot_like_info;

INSERT INTO SPOT_LIKE_INFO (LIKE_IDX, CONTENT_ID, LIKE_CNT) VALUES ( SPOT_LIKE_SEQ.nextval, '1' , 0);
rollback;

select spot_like_seq.nextval from dual;
SELECT SPOT_LIKE_SEQ.NEXTVAL FROM DUAL;

ROLLBACK;

DROP SEQUENCE SPOT_LIKE_SEQ;
CREATE SEQUENCE SPOT_LIKE_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 0;