DROP TABLE USER_PLAN PURGE;
CREATE TABLE USER_PLAN (
    PLAN_NO        NUMBER,
    USER_NO        NUMBER,
    TITLE          VARCHAR2(200),
    CONTENTID      VARCHAR2(10),
    CONTENTTYPEID  VARCHAR2(5),
    ADDR           VARCHAR2(200),
    IMG_SRC        VARCHAR2(300),
    MAPX           VARCHAR2(20),
    MAPY           VARCHAR2(20),
    PLANDATE       VARCHAR2(30),
    PLANDAY        VARCHAR2(30),
    PLANTOTALDATE  VARCHAR2(30),
    STARTDATE      VARCHAR2(20),
    ENDDATE        VARCHAR2(20),
    DESCRIPT       VARCHAR2(1000),
    IS_INSERTAFTER VARCHAR(1) DEFAULT 'N',
    ISACC          VARCHAR(1) DEFAULT 'N'
);

select * from user_plan;

drop table schedule purge;

DROP TABLE PLAN PURGE;
CREATE TABLE PLAN (
    PLAN_NO      NUMBER  CONSTRAINT PLAN_PK PRIMARY KEY,
    USER_NO      NUMBER,
    PLAN_TITLE   VARCHAR2(200),
    PLAN_INFO    VARCHAR2(1000),
    PLAN_IMG     VARCHAR(300),
    PLAN_PRIVATE VARCHAR(1)
);

DROP TABLE PLAN_IMG PURGE;
CREATE TABLE PLAN_IMG (
    PLAN_NO NUMBER,
    USER_NO NUMBER,
    PLAN_IMG VARCHAR2(300),
    REGDATE DATE
);


DELETE FROM USER_PLAN WHERE PLAN_NO = 1 AND IS_INSERTAFTER = 'Y';

MERGE INTO USER_PLAN USING DUAL ON (PLAN_NO = 100 AND TITLE = '휴애리자연생활공원') WHEN MATCHED THEN UPDATE SET PLANDAY = '10', PLANDATE='10', PLANTOTALDATE='10', STARTDATE='10', ENDDATE='10', DESCRIPT=NULL WHEN NOT MATCHED THEN INSERT (PLAN_NO, USER_NO, TITLE, PLANDATE, PLANDAY, PLANTOTALDATE, STARTDATE, ENDDATE, DESCRIPT, IS_INSERTAFTER) VALUES (100, 1, '시발', '10', '10', '10', '10', '10', '10', 'N');
