DROP TABLE USER_PLAN PURGE;
CREATE TABLE USER_PLAN (
    PLAN_NO        NUMBER,
    USER_NO        NUMBER,
    TITLE          VARCHAR2(200),
    CONTENTID      VARCHAR2(10),
    CONTENTTYPEID  VARCHAR2(5),
    ADDR           VARCHAR2(200),
    IMG_SRC        VARCHAR2(300),
    MAPX           VARCHAR2(20),
    MAPY           VARCHAR2(20),
    PLANDATE       VARCHAR2(30),
    PLANDAY        VARCHAR2(30),
    PLANTOTALDATE  VARCHAR2(30),
    STARTDATE      VARCHAR2(20),
    ENDDATE        VARCHAR2(20),
    DESCRIPT       VARCHAR2(1000),
    IS_INSERTAFTER VARCHAR(1) DEFAULT 'N',
    ISACC          VARCHAR(1) DEFAULT 'N'
);

DROP TABLE PLAN PURGE;
CREATE TABLE PLAN (
    PLAN_NO    NUMBER  CONSTRAINT PLAN_PK PRIMARY KEY,
    USER_NO    NUMBER,
    PLAN_TITLE VARCHAR2(200),
    PLAN_INFO  VARCHAR2(1000),
    PLAN_IMG   VARCHAR(300),
    PLAN_PRIVATE VARCHAR(1)
);

DROP TABLE PLAN_IMG PURGE;
CREATE TABLE PLAN_IMG (
    PLAN_NO NUMBER,
    USER_NO NUMBER,
    PLAN_IMG VARCHAR2(300),
    REGDATE DATE
);
